### ISSUE TITLE
Freetype dependency missing from the ubuntu "apt-get install" command.

### ISSUE THREAD

**Issue by DomtronVox** [zhanggyb/BlendInt#1]
On the wiki page https://github.com/zhanggyb/BlendInt/wiki/build the ubuntu "apt-get install" command for   dependencies is missing freetype and is apparently needed  to compile. (at least on ubuntu 14.04) 

On Ubuntu 14.04 the freetype package is called "libfreetype6" or "libfreetype6-dev". (I downloaded the second one though I'm still trying to get BlenderInt to compile but cmake accepts it)

**Comment by zhanggyb** [comment]
Sorry, the instruction of installing packages in Ubuntu is not complete.
I forgot the package names as I haven't used Ubuntu recently.
I'll fix this error ASAP.

**Comment by zhanggyb** [comment]
Hi, I just updated the wiki page for Ubuntu.

In brief:

``` shell
$ sudo apt-get install git g++
$ sudo apt-get install cmake libopenimageio-dev libboost-dev libboost-filesystem-dev libboost-system-dev libboost-thread-dev libfreetype6-dev libfontconfig1-dev mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev
$ sudo apt-get install libxrandr-dev libxinerama-dev libxi-dev libxcursor-dev
$ git clone https://github.com/zhanggyb/BlendInt.git
$ cd BlendInt
$ git submodule update --init extern/glfw
```

Now you can compile:

``` shell
$ git submodule update --init demo
$ mkdir build
$ cd build
$ cmake .. -DWITH_GLFW3_DEMO=TRUE
$ make
$ ./bin/tutorial01
```

**Comment by DomtronVox** [comment]
No need to apologize I'm glad to help. Let me just say that your documentation is way better then others I've seen especially since (as far as I can tell) your the only dev. I may try to keep up to date with the project and at least help out with the Ubuntu docs. From what I've seen this is a very nice project.

_Sent via Hubroid_

**Comment by zhanggyb** [comment]
Thanks!
Until now I'm developing this project alone and (I think) I'm not good at English, so any help on the code or doc is very welcome.
