### ISSUE TITLE
A compiling issue

### ISSUE THREAD

**Issue by shuozhifenxi** [zhanggyb/BlendInt#2]
First thank you for the great work.

And I think in editor/main.cpp, the line 111
model.Print();
should be only for debug not release, because  void StringListModel::Print() is only defined in debug configration.

**Comment by zhanggyb** [comment]
Yes, it's a mistake and will be fixed in the next commit.

I plan to develop a WYSIWYG ui editor based on node system and support XML import/export. But for now the source code in folder "editor" is only used to test the basic framework (I use gtest for unit test, but some test programs cause segment fault in Linux (Fedora and Arch) and I don't know why, everything works fine in OS X)

**Comment by shuozhifenxi** [comment]
Thanks for your reply.

I love the GUI of Blender since the first time I used Blender (in about 2008). I have been hoping to use the similar GUI for my own code from then on. And I have seen people discussed that a lot but all ended with "it is too difficult/ too much to do". 

Your project is the first real attempt I have seen for this. I just can not help but to wonder what is your motivation for this project? And are you working alone for this project?

Thank you again for all your efforts.

**Comment by zhanggyb** [comment]
The motivation is: I wanted to try to develop a simple cross-platform toolkit to provide equal look and feel on different platforms.

And yes, I'm working alone. I don't mind this until this project reaches 0.1 vesion.

See [here](https://github.com/zhanggyb/BlendInt/wiki#the-motivation) and [here](https://github.com/zhanggyb/BlendInt/wiki/roadmap).

I'll leave this issue open for a while but you can compile with the latest commit now. Please be noted I haven't started to program the UI editor, running it will just give you a blank window.

**Comment by zhanggyb** [comment]
OK, time to close this issue.
I still need time to fix some critical bugs and rewrite the event module before start to program the UI editor. This may take 2 months.
If you get compile error again, please reopen or file new bug to me.
